import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Catalog } from './catalog';
import type { ResolvedConfig } from './config';
import { collectParams, renderParamType } from './params';

export const VIRTUAL_ID = 'virtual:verbaly';

export function generateRuntimeModule(cfg: ResolvedConfig): string {
  const others = cfg.locales.filter((locale) => locale !== cfg.sourceLocale);
  const src = JSON.stringify(cfg.sourceLocale);
  const loaders = others
    .map((locale) => `  ${JSON.stringify(locale)}: () => import('${VIRTUAL_ID}/locale/${locale}'),`)
    .join('\n');

  return `import { createVerbaly } from 'verbaly';
import source from '${VIRTUAL_ID}/locale/${cfg.sourceLocale}';

const loaders = {
${loaders}
};
const loaded = new Set([${src}]);

const v = createVerbaly({
  locale: ${src},
  fallback: ${src},
  messages: { [${src}]: source },
});

export const verbaly = v;
export const t = v.t;

export function getLocale() {
  return v.locale;
}

export function subscribe(listener) {
  return v.subscribe(listener);
}

export async function setLocale(locale) {
  const target = loaders[locale] ? locale : locale.split('-')[0];
  if (!loaded.has(target) && loaders[target]) {
    const mod = await loaders[target]();
    v.addMessages(target, mod.default);
    loaded.add(target);
  }
  v.setLocale(locale);
}
`;
}

export function generateLocaleModule(catalog: Catalog): string {
  return `export default ${JSON.stringify(catalog)};\n`;
}

export function generateDts(entries: Map<string, string>): string {
  const lines: string[] = [];
  for (const [key, message] of [...entries.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const params = collectParams(message);
    if (params.size === 0) {
      lines.push(`    ${JSON.stringify(key)}: never;`);
    } else {
      const fields = [...params.entries()]
        .map(([name, types]) => `${JSON.stringify(name)}: ${renderParamType(types)}`)
        .join('; ');
      lines.push(`    ${JSON.stringify(key)}: { ${fields} };`);
    }
  }

  return `// generated by verbaly — do not edit
declare module 'virtual:verbaly' {
  export interface VerbalyMessages {
${lines.join('\n')}
  }
  export type VerbalyKey = keyof VerbalyMessages & string;

  export const verbaly: import('verbaly').Verbaly<VerbalyKey>;

  export function t<K extends VerbalyKey>(
    key: K,
    ...args: [VerbalyMessages[K]] extends [never] ? [] : [VerbalyMessages[K]]
  ): string;
  export function t(strings: TemplateStringsArray, ...values: unknown[]): string;

  export function setLocale(locale: string): Promise<void>;
  export function getLocale(): string;
  export function subscribe(listener: () => void): () => void;
}

declare module 'virtual:verbaly/locale/*' {
  const messages: Record<string, string>;
  export default messages;
}
`;
}

export function writeDts(cfg: ResolvedConfig, entries: Map<string, string>): void {
  writeFileSync(join(cfg.root, 'verbaly.d.ts'), generateDts(entries));
}
